import stackCssIcon from '../utils/icons/css3.svg';
import stackExpressIcon from '../utils/icons/express.svg';
import stackHtmlIcon from '../utils/icons/html5.svg';
import stackJavascriptIcon from '../utils/icons/javascript.svg';
import stackJestIcon from '../utils/icons/jest.svg';
import stackMuiIcon from '../utils/icons/materialUI.svg';
import stackNodeJsIcon from '../utils/icons/nodeJs.svg';
import stackPostgreSQLIcon from '../utils/icons/postgreSQL.svg';
import stackPostmanIcon from '../utils/icons/postman.svg';
import stackReactIcon from '../utils/icons/react.svg';
import stackReduxIcon from '../utils/icons/redux.svg';
import stackSequelizeIcon from '../utils/icons/sequelize.svg';
import stackSwaggerIcon from '../utils/icons/swagger.svg';
import stackTypescriptIcon from '../utils/icons/typescript.svg';
import stackAngularIcon from '../utils/icons/angular.svg';
import stackNextJsIcon from '../utils/icons/nextjs2.svg';
import stackNestJsIcon from '../utils/icons/nestJs.svg';

export const cssIcon = stackCssIcon;
export const expressIcon = stackExpressIcon;
export const htmlIcon = stackHtmlIcon;
export const javascriptIcon = stackJavascriptIcon;
export const jestIcon = stackJestIcon;
export const muiIcon = stackMuiIcon;
export const nodeJsIcon = stackNodeJsIcon;
export const postgresqlIcon = stackPostgreSQLIcon;
export const postmanIcon = stackPostmanIcon;
export const reactIcon = stackReactIcon;
export const reduxIcon = stackReduxIcon;
export const sequelizeIcon = stackSequelizeIcon;
export const swaggerIcon = stackSwaggerIcon;
export const typescriptIcon = stackTypescriptIcon;
export const angularIcon = stackAngularIcon;
export const nextJsIcon = stackNextJsIcon;
export const nestJsIcon = stackNestJsIcon;